--Inserindo Locais
INSERT INTO Local (Descricao, Latitude, Longitude) VALUES ('Itajaí',-122,20)
INSERT INTO Local (Descricao, Latitude, Longitude) VALUES ('Balneário Camboriú',-122,20)
INSERT INTO Local (Descricao, Latitude, Longitude) VALUES ('Camboriú',-11,10)
INSERT INTO Local (Descricao, Latitude, Longitude) VALUES ('Brusque',-122,20)
INSERT INTO Local (Descricao, Latitude, Longitude) VALUES ('Timbó',-122,20)
INSERT INTO Local (Descricao, Latitude, Longitude) VALUES ('Blumenau',-122,20)

--Inserindo Climas
INSERT INTO Clima (Descricao_Longa, Descricao_Curta, TemperaturaMaxima, TemperaturaMinima, Umidade, Data_Clima, Direcao_Vento)
VALUES ('Nuvens com clima ensolarado','Nuvens com sol',20,10,100,GETDATE(),'Norte')
INSERT INTO Clima (Descricao_Longa, Descricao_Curta, TemperaturaMaxima, TemperaturaMinima, Umidade, Data_Clima, Direcao_Vento)
VALUES ('Ensolarado','Ensolarado',20,10,100,GETDATE(),'Norte')
INSERT INTO Clima (Descricao_Longa, Descricao_Curta, TemperaturaMaxima, TemperaturaMinima, Umidade, Data_Clima, Direcao_Vento)
VALUES ('Nublado','Coberto totalmente com nuvens',20,10,100,GETDATE(),'Norte')
INSERT INTO Clima (Descricao_Longa, Descricao_Curta, TemperaturaMaxima, TemperaturaMinima, Umidade, Data_Clima, Direcao_Vento)
VALUES ('Chuvoso','Chuva total',20,10,100,GETDATE(),'Norte')
INSERT INTO Clima (Descricao_Longa, Descricao_Curta, TemperaturaMaxima, TemperaturaMinima, Umidade, Data_Clima, Direcao_Vento)
VALUES ('Neve','Nevasca forte',20,10,100,GETDATE(),'Norte')

--Inserindo combinações de Clima e Local
INSERT INTO ClimaTempo(IdLocal,IdClima,Data_Clima_Tempo) VALUES (1,1,GETDATE())
INSERT INTO ClimaTempo(IdLocal,IdClima,Data_Clima_Tempo) VALUES (1,2,GETDATE())
INSERT INTO ClimaTempo(IdLocal,IdClima,Data_Clima_Tempo) VALUES (1,3,GETDATE())
INSERT INTO ClimaTempo(IdLocal,IdClima,Data_Clima_Tempo) VALUES (1,4,GETDATE())
INSERT INTO ClimaTempo(IdLocal,IdClima,Data_Clima_Tempo) VALUES (1,5,GETDATE())
INSERT INTO ClimaTempo(IdLocal,IdClima,Data_Clima_Tempo) VALUES (1,6,GETDATE())

INSERT INTO ClimaTempo(IdLocal,IdClima,Data_Clima_Tempo) VALUES (2,1,GETDATE())
INSERT INTO ClimaTempo(IdLocal,IdClima,Data_Clima_Tempo) VALUES (2,2,GETDATE())
INSERT INTO ClimaTempo(IdLocal,IdClima,Data_Clima_Tempo) VALUES (2,3,GETDATE())
INSERT INTO ClimaTempo(IdLocal,IdClima,Data_Clima_Tempo) VALUES (2,4,GETDATE())
INSERT INTO ClimaTempo(IdLocal,IdClima,Data_Clima_Tempo) VALUES (2,5,GETDATE())
INSERT INTO ClimaTempo(IdLocal,IdClima,Data_Clima_Tempo) VALUES (2,6,GETDATE())

INSERT INTO ClimaTempo(IdLocal,IdClima,Data_Clima_Tempo) VALUES (3,1,GETDATE())
INSERT INTO ClimaTempo(IdLocal,IdClima,Data_Clima_Tempo) VALUES (3,2,GETDATE())
INSERT INTO ClimaTempo(IdLocal,IdClima,Data_Clima_Tempo) VALUES (3,3,GETDATE())
INSERT INTO ClimaTempo(IdLocal,IdClima,Data_Clima_Tempo) VALUES (3,4,GETDATE())
INSERT INTO ClimaTempo(IdLocal,IdClima,Data_Clima_Tempo) VALUES (3,5,GETDATE())
INSERT INTO ClimaTempo(IdLocal,IdClima,Data_Clima_Tempo) VALUES (3,6,GETDATE())

INSERT INTO ClimaTempo(IdLocal,IdClima,Data_Clima_Tempo) VALUES (4,1,GETDATE())
INSERT INTO ClimaTempo(IdLocal,IdClima,Data_Clima_Tempo) VALUES (4,2,GETDATE())
INSERT INTO ClimaTempo(IdLocal,IdClima,Data_Clima_Tempo) VALUES (4,3,GETDATE())
INSERT INTO ClimaTempo(IdLocal,IdClima,Data_Clima_Tempo) VALUES (4,4,GETDATE())
INSERT INTO ClimaTempo(IdLocal,IdClima,Data_Clima_Tempo) VALUES (4,5,GETDATE())
INSERT INTO ClimaTempo(IdLocal,IdClima,Data_Clima_Tempo) VALUES (4,6,GETDATE())

INSERT INTO ClimaTempo(IdLocal,IdClima,Data_Clima_Tempo) VALUES (5,1,GETDATE())
INSERT INTO ClimaTempo(IdLocal,IdClima,Data_Clima_Tempo) VALUES (5,2,GETDATE())
INSERT INTO ClimaTempo(IdLocal,IdClima,Data_Clima_Tempo) VALUES (5,3,GETDATE())
INSERT INTO ClimaTempo(IdLocal,IdClima,Data_Clima_Tempo) VALUES (5,4,GETDATE())
INSERT INTO ClimaTempo(IdLocal,IdClima,Data_Clima_Tempo) VALUES (5,5,GETDATE())
INSERT INTO ClimaTempo(IdLocal,IdClima,Data_Clima_Tempo) VALUES (5,6,GETDATE())
